import { Locale, defaultLocale, isValidLocale, locales } from "@/i18n/config";
import { getMessages } from "@/i18n/get-intl";
import IntlClientProvider from "@/i18n/IntlClientProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 정적 생성을 위한 locale 파라미터 생성
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function LocaleLayout({
  children,
  params,
}: LocaleLayoutProps) {
  const { locale } = await params;
  const validLocale: Locale = isValidLocale(locale) ? locale : defaultLocale;
  const messages = await getMessages(validLocale);

  return (
    <html lang={validLocale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <IntlClientProvider locale={validLocale} messages={messages}>
          {children}
        </IntlClientProvider>
      </body>
    </html>
  );
}
